// Global Region Database mapping ISO-2 codes, official dial prefixes, and names
export const WORLD_REGIONS = [
  { code: "+962", name: "Jordan", id: "jo", short: "JO" },
  { code: "+966", name: "Saudi Arabia", id: "sa", short: "SA" },
  { code: "+971", name: "United Arab Emirates", id: "ae", short: "AE" },
  { code: "+1", name: "United States", id: "us", short: "US" },
  { code: "+93", name: "Afghanistan", id: "af", short: "AF" },
  { code: "+355", name: "Albania", id: "al", short: "AL" },
  { code: "+213", name: "Algeria", id: "dz", short: "DZ" },
  { code: "+376", name: "Andorra", id: "ad", short: "AD" },
  { code: "+244", name: "Angola", id: "ao", short: "AO" },
  { code: "+1-268", name: "Antigua and Barbuda", id: "ag", short: "AG" },
  { code: "+54", name: "Argentina", id: "ar", short: "AR" },
  { code: "+374", name: "Armenia", id: "am", short: "AM" },
  { code: "+61", name: "Australia", id: "au", short: "AU" },
  { code: "+43", name: "Austria", id: "at", short: "AT" },
  { code: "+994", name: "Azerbaijan", id: "az", short: "AZ" },
  { code: "+1-242", name: "Bahamas", id: "bs", short: "BS" },
  { code: "+973", name: "Bahrain", id: "bh", short: "BH" },
  { code: "+880", name: "Bangladesh", id: "bd", short: "BD" },
  { code: "+1-246", name: "Barbados", id: "bb", short: "BB" },
  { code: "+375", name: "Belarus", id: "by", short: "BY" },
  { code: "+32", name: "Belgium", id: "be", short: "BE" },
  { code: "+501", name: "Belize", id: "bz", short: "BZ" },
  { code: "+229", name: "Benin", id: "bj", short: "BJ" },
  { code: "+975", name: "Bhutan", id: "bt", short: "BT" },
  { code: "+591", name: "Bolivia", id: "bo", short: "BO" },
  { code: "+387", name: "Bosnia and Herzegovina", id: "ba", short: "BA" },
  { code: "+267", name: "Botswana", id: "bw", short: "BW" },
  { code: "+55", name: "Brazil", id: "br", short: "BR" },
  { code: "+673", name: "Brunei", id: "bn", short: "BN" },
  { code: "+359", name: "Bulgaria", id: "bg", short: "BG" },
  { code: "+226", name: "Burkina Faso", id: "bf", short: "BF" },
  { code: "+257", name: "Burundi", id: "bi", short: "BI" },
  { code: "+238", name: "Cabo Verde", id: "cv", short: "CV" },
  { code: "+855", name: "Cambodia", id: "kh", short: "KH" },
  { code: "+237", name: "Cameroon", id: "cm", short: "CM" },
  { code: "+1", name: "Canada", id: "ca", short: "CA" },
  { code: "+236", name: "Central African Republic", id: "cf", short: "CF" },
  { code: "+235", name: "Chad", id: "td", short: "TD" },
  { code: "+56", name: "Chile", id: "cl", short: "CL" },
  { code: "+86", name: "China", id: "cn", short: "CN" },
  { code: "+57", name: "Colombia", id: "co", short: "CO" },
  { code: "+269", name: "Comoros", id: "km", short: "KM" },
  { code: "+242", name: "Congo (Brazzaville)", id: "cg", short: "CG" },
  { code: "+243", name: "Congo (Kinshasa)", id: "cd", short: "CD" },
  { code: "+506", name: "Costa Rica", id: "cr", short: "CR" },
  { code: "+225", name: "Cote d'Ivoire", id: "ci", short: "CI" },
  { code: "+385", name: "Croatia", id: "hr", short: "HR" },
  { code: "+53", name: "Cuba", id: "cu", short: "CU" },
  { code: "+357", name: "Cyprus", id: "cy", short: "CY" },
  { code: "+420", name: "Czechia", id: "cz", short: "CZ" },
  { code: "+45", name: "Denmark", id: "dk", short: "DK" },
  { code: "+253", name: "Djibouti", id: "dj", short: "DJ" },
  { code: "+1-767", name: "Dominica", id: "dm", short: "DM" },
  { code: "+1-809", name: "Dominican Republic", id: "do", short: "DO" },
  { code: "+593", name: "Ecuador", id: "ec", short: "EC" },
  { code: "+20", name: "Egypt", id: "eg", short: "EG" },
  { code: "+503", name: "El Salvador", id: "sv", short: "SV" },
  { code: "+240", name: "Equatorial Guinea", id: "gq", short: "GQ" },
  { code: "+291", name: "Eritrea", id: "er", short: "ER" },
  { code: "+372", name: "Estonia", id: "ee", short: "EE" },
  { code: "+268", name: "Eswatini", id: "sz", short: "SZ" },
  { code: "+251", name: "Ethiopia", id: "et", short: "ET" },
  { code: "+679", name: "Fiji", id: "fj", short: "FJ" },
  { code: "+358", name: "Finland", id: "fi", short: "FI" },
  { code: "+33", name: "France", id: "fr", short: "FR" },
  { code: "+241", name: "Gabon", id: "ga", short: "GA" },
  { code: "+220", name: "Gambia", id: "gm", short: "GM" },
  { code: "+995", name: "Georgia", id: "ge", short: "GE" },
  { code: "+49", name: "Germany", id: "de", short: "DE" },
  { code: "+233", name: "Ghana", id: "gh", short: "GH" },
  { code: "+30", name: "Greece", id: "gr", short: "GR" },
  { code: "+1-473", name: "Grenada", id: "gd", short: "GD" },
  { code: "+502", name: "Guatemala", id: "gt", short: "GT" },
  { code: "+224", name: "Guinea", id: "gn", short: "GN" },
  { code: "+245", name: "Guinea-Bissau", id: "gw", short: "GW" },
  { code: "+592", name: "Guyana", id: "gy", short: "GY" },
  { code: "+509", name: "Haiti", id: "ht", short: "HT" },
  { code: "+504", name: "Honduras", id: "hn", short: "HN" },
  { code: "+36", name: "Hungary", id: "hu", short: "HU" },
  { code: "+354", name: "Iceland", id: "is", short: "IS" },
  { code: "+91", name: "India", id: "in", short: "IN" },
  { code: "+62", name: "Indonesia", id: "id", short: "ID" },
  { code: "+98", name: "Iran", id: "ir", short: "IR" },
  { code: "+964", name: "Iraq", id: "iq", short: "IQ" },
  { code: "+353", name: "Ireland", id: "ie", short: "IE" },
  { code: "+972", name: "Israel", id: "il", short: "IL" },
  { code: "+39", name: "Italy", id: "it", short: "IT" },
  { code: "+1-876", name: "Jamaica", id: "jm", short: "JM" },
  { code: "+81", name: "Japan", id: "jp", short: "JP" },
  { code: "+7", name: "Kazakhstan", id: "kz", short: "KZ" },
  { code: "+254", name: "Kenya", id: "ke", short: "KE" },
  { code: "+686", name: "Kiribati", id: "ki", short: "KI" },
  { code: "+965", name: "Kuwait", id: "kw", short: "KW" },
  { code: "+996", name: "Kyrgyzstan", id: "kg", short: "KG" },
  { code: "+856", name: "Laos", id: "la", short: "LA" },
  { code: "+371", name: "Latvia", id: "lv", short: "LV" },
  { code: "+961", name: "Lebanon", id: "lb", short: "LB" },
  { code: "+266", name: "Lesotho", id: "ls", short: "LS" },
  { code: "+231", name: "Liberia", id: "lr", short: "LR" },
  { code: "+218", name: "Libya", id: "ly", short: "LY" },
  { code: "+423", name: "Liechtenstein", id: "li", short: "LI" },
  { code: "+370", name: "Lithuania", id: "lt", short: "LT" },
  { code: "+352", name: "Luxembourg", id: "lu", short: "LU" },
  { code: "+389", name: "Madagascar", id: "mg", short: "MG" },
  { code: "+265", name: "Malawi", id: "mw", short: "MW" },
  { code: "+60", name: "Malaysia", id: "my", short: "MY" },
  { code: "+960", name: "Maldives", id: "mv", short: "MV" },
  { code: "+223", name: "Mali", id: "ml", short: "ML" },
  { code: "+356", name: "Malta", id: "mt", short: "MT" },
  { code: "+692", name: "Marshall Islands", id: "mh", short: "MH" },
  { code: "+222", name: "Mauritania", id: "mr", short: "MR" },
  { code: "+230", name: "Mauritius", id: "mu", short: "MU" },
  { code: "+52", name: "Mexico", id: "mx", short: "MX" },
  { code: "+691", name: "Micronesia", id: "fm", short: "FM" },
  { code: "+373", name: "Moldova", id: "md", short: "MD" },
  { code: "+377", name: "Monaco", id: "mc", short: "MC" },
  { code: "+976", name: "Mongolia", id: "mn", short: "MN" },
  { code: "+382", name: "Montenegro", id: "me", short: "ME" },
  { code: "+212", name: "Morocco", id: "ma", short: "MA" },
  { code: "+258", name: "Mozambique", id: "mz", short: "MZ" },
  { code: "+95", name: "Myanmar", id: "mm", short: "MM" },
  { code: "+264", name: "Namibia", id: "na", short: "NA" },
  { code: "+674", name: "Nauru", id: "nr", short: "NR" },
  { code: "+977", name: "Nepal", id: "np", short: "NP" },
  { code: "+31", name: "Netherlands", id: "nl", short: "NL" },
  { code: "+64", name: "New Zealand", id: "nz", short: "NZ" },
  { code: "+505", name: "Nicaragua", id: "ni", short: "NI" },
  { code: "+227", name: "Niger", id: "ne", short: "NE" },
  { code: "+234", name: "Nigeria", id: "ng", short: "NG" },
  { code: "+850", name: "North Korea", id: "kp", short: "KP" },
  { code: "+389", name: "North Macedonia", id: "mk", short: "MK" },
  { code: "+47", name: "Norway", id: "no", short: "NO" },
  { code: "+968", name: "Oman", id: "om", short: "OM" },
  { code: "+92", name: "Pakistan", id: "pk", short: "PK" },
  { code: "+680", name: "Palau", id: "pw", short: "PW" },
  { code: "+970", name: "Palestine", id: "ps", short: "PS" },
  { code: "+507", name: "Panama", id: "pa", short: "PA" },
  { code: "+675", name: "Papua New Guinea", id: "pg", short: "PG" },
  { code: "+595", name: "Paraguay", id: "py", short: "PY" },
  { code: "+51", name: "Peru", id: "pe", short: "PE" },
  { code: "+63", name: "Philippines", id: "ph", short: "PH" },
  { code: "+48", name: "Poland", id: "pl", short: "PL" },
  { code: "+351", name: "Portugal", id: "pt", short: "PT" },
  { code: "+974", name: "Qatar", id: "qa", short: "QA" },
  { code: "+40", name: "Romania", id: "ro", short: "RO" },
  { code: "+7", name: "Russia", id: "ru", short: "RU" },
  { code: "+250", name: "Rwanda", id: "rw", short: "RW" },
  { code: "+1-869", name: "Saint Kitts and Nevis", id: "kn", short: "KN" },
  { code: "+1-758", name: "Saint Lucia", id: "lc", short: "LC" },
  { code: "+1-784", name: "Saint Vincent", id: "vc", short: "VC" },
  { code: "+685", name: "Samoa", id: "ws", short: "WS" },
  { code: "+378", name: "San Marino", id: "sm", short: "SM" },
  { code: "+239", name: "Sao Tome and Principe", id: "st", short: "ST" },
  { code: "+221", name: "Senegal", id: "sn", short: "SN" },
  { code: "+381", name: "Serbia", id: "rs", short: "RS" },
  { code: "+248", name: "Seychelles", id: "sc", short: "SC" },
  { code: "+232", name: "Sierra Leone", id: "sl", short: "SL" },
  { code: "+65", name: "Singapore", id: "sg", short: "SG" },
  { code: "+421", name: "Slovakia", id: "sk", short: "SK" },
  { code: "+386", name: "Slovenia", id: "si", short: "SI" },
  { code: "+677", name: "Solomon Islands", id: "sb", short: "SB" },
  { code: "+252", name: "Somalia", id: "so", short: "SO" },
  { code: "+27", name: "South Africa", id: "za", short: "ZA" },
  { code: "+82", name: "South Korea", id: "kr", short: "KR" },
  { code: "+211", name: "South Sudan", id: "ss", short: "SS" },
  { code: "+34", name: "Spain", id: "es", short: "ES" },
  { code: "+94", name: "Sri Lanka", id: "lk", short: "LK" },
  { code: "+249", name: "Sudan", id: "sd", short: "SD" },
  { code: "+597", name: "Suriname", id: "sr", short: "SR" },
  { code: "+46", name: "Sweden", id: "se", short: "SE" },
  { code: "+41", name: "Switzerland", id: "ch", short: "CH" },
  { code: "+963", name: "Syria", id: "sy", short: "SY" },
  { code: "+886", name: "Taiwan", id: "tw", short: "TW" },
  { code: "+992", name: "Tajikistan", id: "tj", short: "TJ" },
  { code: "+255", name: "Tanzania", id: "tz", short: "TZ" },
  { code: "+66", name: "Thailand", id: "th", short: "TH" },
  { code: "+228", name: "Togo", id: "tg", short: "TG" },
  { code: "+676", name: "Tonga", id: "to", short: "TO" },
  { code: "+1-868", name: "Trinidad and Tobago", id: "tt", short: "TT" },
  { code: "+216", name: "Tunisia", id: "tn", short: "TN" },
  { code: "+90", name: "Turkey", id: "tr", short: "TR" },
  { code: "+993", name: "Turkmenistan", id: "tm", short: "TM" },
  { code: "+688", name: "Tuvalu", id: "tv", short: "TV" },
  { code: "+256", name: "Uganda", id: "ug", short: "UG" },
  { code: "+380", name: "Ukraine", id: "ua", short: "UA" },
  { code: "+44", name: "United Kingdom", id: "gb", short: "GB" },
  { code: "+598", name: "Uruguay", id: "uy", short: "UY" },
  { code: "+998", name: "Uzbekistan", id: "uz", short: "UZ" },
  { code: "+678", name: "Vanuatu", id: "vu", short: "VU" },
  { code: "+58", name: "Venezuela", id: "ve", short: "VE" },
  { code: "+84", name: "Vietnam", id: "vn", short: "VN" },
  { code: "+967", name: "Yemen", id: "ye", short: "YE" },
  { code: "+260", name: "Zambia", id: "zm", short: "ZM" },
  { code: "+263", name: "Zimbabwe", id: "zw", short: "ZW" }
];